States = ["Uzbekistan","Turkiya","Canada","Korea","Shvesariya"]
cons_states = States.copy()
print(len(States))
print(sorted(States))
print(sorted(States,reverse=True))
print(States)
States.reverse()
print(States)
States.sort()
print(States)
States.sort(reverse=True)
print(States)
